"""initial schema: pgvector ext + all tables + HNSW/btree indexes

Revision ID: 0001_initial
Revises:
Create Date: 2024-01-01 00:00:00

Hand-written (not autogenerated): autogenerate omits ``CREATE EXTENSION`` and the
HNSW ``vector_cosine_ops`` indexes, so those are emitted via ``op.execute``. The
table/column shape mirrors ``backend/db/models.py``.
"""
# allow: SIZE_OK — one indivisible initial migration (12 tables + their indexes);
# splitting a single revision's upgrade()/downgrade() is not possible.

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("google_access_token", sa.String(), nullable=True),
        sa.Column("google_refresh_token", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "conversation",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("user.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "task",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("user.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "conversation_id",
            sa.Uuid(),
            sa.ForeignKey("conversation.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("progress", postgresql.JSONB(), nullable=True),
        sa.Column("checkpoint", postgresql.JSONB(), nullable=True),
        sa.Column("result", postgresql.JSONB(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column(
            "parent_task_id",
            sa.Uuid(),
            sa.ForeignKey("task.id"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "message",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "conversation_id",
            sa.Uuid(),
            sa.ForeignKey("conversation.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("user.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("task_id", sa.Uuid(), sa.ForeignKey("task.id"), nullable=True),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("intent", postgresql.JSONB(), nullable=True),
        sa.Column("classification", postgresql.JSONB(), nullable=True),
        sa.Column("entities", postgresql.JSONB(), nullable=True),
        sa.Column("plan", postgresql.JSONB(), nullable=True),
        sa.Column("actions_taken", postgresql.JSONB(), nullable=True),
        sa.Column("pending_actions", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "gmail_datasource",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("user.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("email_id", sa.String(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=True),
        sa.Column("sender_email_id", sa.String(), nullable=True),
        sa.Column("receiver_email_id", sa.String(), nullable=True),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("labels", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("user_id", "email_id", name="uq_gmail_datasource_user_email"),
    )

    op.create_table(
        "gcal_datasource",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("user.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attendees", postgresql.ARRAY(sa.String()), nullable=False),
        sa.UniqueConstraint("user_id", "event_id", name="uq_gcal_datasource_user_event"),
    )

    op.create_table(
        "gdrive_datasource",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("user.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("file_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("mime_type", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("owner", sa.String(), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("user_id", "file_id", name="uq_gdrive_datasource_user_file"),
    )

    op.create_table(
        "gmail_vector_store",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column(
            "datasource_id",
            sa.Uuid(),
            sa.ForeignKey("gmail_datasource.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.String(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(1024), nullable=True),
        sa.UniqueConstraint("datasource_id", "chunk_index", name="uq_gmail_vs_ds_chunk"),
    )

    op.create_table(
        "gcal_vector_store",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column(
            "datasource_id",
            sa.Uuid(),
            sa.ForeignKey("gcal_datasource.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.String(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(1024), nullable=True),
        sa.UniqueConstraint("datasource_id", "chunk_index", name="uq_gcal_vs_ds_chunk"),
    )

    op.create_table(
        "gdrive_vector_store",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column(
            "datasource_id",
            sa.Uuid(),
            sa.ForeignKey("gdrive_datasource.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.String(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(1024), nullable=True),
        sa.UniqueConstraint("datasource_id", "chunk_index", name="uq_gdrive_vs_ds_chunk"),
    )

    op.create_table(
        "actions_log",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("user.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "conversation_id",
            sa.Uuid(),
            sa.ForeignKey("conversation.id"),
            nullable=True,
        ),
        sa.Column("task_id", sa.Uuid(), sa.ForeignKey("task.id"), nullable=True),
        sa.Column("tool", sa.String(), nullable=False),
        sa.Column("args", postgresql.JSONB(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("result", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "sync_status",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("user.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("service", sa.String(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("cursor", sa.String(), nullable=True),
        sa.UniqueConstraint("user_id", "service", name="uq_sync_status_user_service"),
    )

    # btree indexes (PLAN.md l.250-255 + DATA_INGESTION §6).
    op.create_index("ix_user_email", "user", ["email"], unique=True)
    op.create_index("ix_message_conversation_seq", "message", ["conversation_id", "seq"])
    op.create_index("ix_task_user_status_created", "task", ["user_id", "status", "created_at"])
    op.create_index("ix_task_parent", "task", ["parent_task_id"])
    op.create_index("ix_gmail_ds_user_received", "gmail_datasource", ["user_id", "received_at"])
    op.create_index("ix_gmail_ds_sender", "gmail_datasource", ["sender_email_id"])
    op.create_index("ix_gcal_ds_user_start", "gcal_datasource", ["user_id", "start_at"])
    op.create_index("ix_gdrive_ds_user_modified", "gdrive_datasource", ["user_id", "modified_at"])
    for svc in ("gmail", "gcal", "gdrive"):
        op.create_index(f"ix_{svc}_vs_user", f"{svc}_vector_store", ["user_id"])
        op.create_index(f"ix_{svc}_vs_datasource", f"{svc}_vector_store", ["datasource_id"])

    # GIN over the calendar attendees array (structured attendee prefilter).
    op.execute("CREATE INDEX ix_gcal_ds_attendees ON gcal_datasource USING gin (attendees)")

    # HNSW cosine ANN over each chunk embedding (autogenerate cannot emit these).
    for svc in ("gmail", "gcal", "gdrive"):
        op.execute(
            f"CREATE INDEX ix_{svc}_vs_embedding_hnsw ON {svc}_vector_store "
            "USING hnsw (embedding vector_cosine_ops)"
        )


def downgrade() -> None:
    op.drop_table("sync_status")
    op.drop_table("actions_log")
    op.drop_table("gdrive_vector_store")
    op.drop_table("gcal_vector_store")
    op.drop_table("gmail_vector_store")
    op.drop_table("gdrive_datasource")
    op.drop_table("gcal_datasource")
    op.drop_table("gmail_datasource")
    op.drop_table("message")
    op.drop_table("task")
    op.drop_table("conversation")
    op.drop_table("user")
    op.execute("DROP EXTENSION IF EXISTS vector")
